name: Test SDK with PHPUnit
on: [push, pull_request]

jobs:
  build:
    name: Test SDK | PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.3', '8.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Composer
        run: |
          wget -qO- composer-setup.php https://getcomposer.org/installer | php -- composer-setup.php
          composer --version

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHPUnit e Dependencies
        run: |
          composer install --ignore-platform-req php

      - name: Build Docker Server
        run: docker-compose -f upload/system/library/PagSeguro/tests/server/docker-compose.yaml up -d

      - name: Run Tests
        run: |
          composer tdd

        run: |
